### ISSUE TITLE
Support Elasticsearch as additional backend

### ISSUE THREAD

**Issue by Madhu1512** [uber/jaeger#140]
is there any plan to support Elasticsearch as additional backend? I will be useful for those who want to leverage there existing elasticsearch cluster. Zipkins and Hawkular APM uses elasticsearch as backend.

**Comment by jpkrohling** [comment]
I'd rather see a way (or an example, as I suspect this shouldn't be hard to accomplish) to stream data from Cassandra into an external system. This way, data can be sent to Elasticsearch for aggregations, to a metrics system for alerting, to a BI solution for dashboards and so on.

**Comment by adriancole** [comment]
Unsolicited advice.. the main difference between OpenZipkin and Zipkin was
that we decoupled the project from internal decisions made at Twitter.
Everything else came from there.

It is a tough choice to spend effort on other data stores, but most of the
time when a user asks to use something different it is because they dont
have the ability to support the de facto.

Not saying this is the case here, but a couple years ago when Zipkin had
the same problem of c* only, we wouldnt have been able to solve that by
requiring c* and also another datastore. The lack of c* experience was the
issue.

On 3 May 2017 11:09 pm, "Juraci Paixão Kröhling" <notifications@github.com>
wrote:

I'd rather see a way (or an example, as I suspect this shouldn't be hard to
accomplish) to stream data from Cassandra into an external system. This
way, data can be sent to Elasticsearch for aggregations, to a metrics
system for alerting, to a BI solution for dashboards and so on.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/uber/jaeger/issues/140#issuecomment-298940320>, or mute
the thread

**Comment by yurishkuro** [comment]
@adriancole would you say it was MySQL support that provided the most uplift? I would guess running ES is not much easier than running C*. 

We do have some ES implementation that we used for original prototyping, but it was against the old data model, so not sure how much help it would be now. And implementing the integration tests against real ES would be a requirement to officially support ES as a backend store.

cc @objectiser @pavolloffay

**Comment by adriancole** [comment]
>
> @adriancole <https://github.com/adriancole> would you say it was MySQL
> support that provided the most uplift?
>
Hard to say because mysql was running long before ES was. Making it an easy
to consume of the package wasn't so, once remedied, mysql indeed did help
folks start.

> I would guess running ES is not much easier than running C*.
>
I've not done a survey, but it seems the case people look for one or the
other based on experience. For example, if they already have experience in
c*, they want c*. If they already have experience w/ ES, they want ES. I
don't know much about folks who have neither and what leads them to choose
either...

**Comment by objectiser** [comment]
It would be good to offer ES as an option, even though it may potentially not scale as well as C*, as it offers better analysis capabilities in conjunction with Kibana.

**Comment by hwinkel** [comment]
What about druid.io anybody considered that? From my high level perspectiv it sounds like it could fir as well.

**Comment by yurishkuro** [comment]
ES support has been added in https://github.com/uber/jaeger/releases/tag/v0.6.0
