### ISSUE TITLE
near-zero intrusive tracing for golang

### ISSUE THREAD

**Issue by yuekui2** [uber/jaeger#162]
Dapper paper explains near-zero intrusive tracing for language like c++, java. For golang, what I know is passing down the tracing needed info via context. This means the context has to be explicitly passed down, **without any interruption**.This makes migrating old code base to tracing difficult, as there is no simple way to enforce that context is correctly passing down. Any suggestion on better way to achieve this?

Thanks.
-Kui

**Comment by yurishkuro** [comment]
I am not aware of another way in Go, since it has no equivalent to thread-local storage. Even _with_ thread local storage, given that Go highly encourages the use of goroutines, the context still needs to be transferred from one goroutine to another (similar problem exists in Java).

Note that Google, for all the lessons they learnt from Dapper, says:

https://blog.golang.org/context

> At Google, we require that Go programmers pass a Context parameter as the first argument to every function on the call path between incoming and outgoing requests. This allows Go code developed by many different teams to interoperate well. It provides simple control over timeouts and cancelation and ensures that critical values like security credentials transit Go programs properly.

**Comment by yuekui2** [comment]
Thanks for answering. That makes sense. Could you also shed more insight about java? That is also something we need to support as well.

**Comment by yurishkuro** [comment]
opentracing-java has recently added support for in-process context propagation into the main API, I suggest reviewing that & the corresponding docs (specifically around "active span"). We have not yet upgraded Jaeger Java client to that version.

**Comment by yuekui2** [comment]
Thanks a lot.
