### ISSUE TITLE
How to start from config file?

### ISSUE THREAD

**Issue by JodeZer** [uber/jaeger#170]
Hi, we are doing some research on jaeger for tracing. 
Is there a way to boot from a conf file?

**Comment by black-adder** [comment]
Hi, at the moment, we only support command line arguments to start jaeger.

**Comment by yurishkuro** [comment]
@JodeZer you can have a wrapper script that reads the config file and translates it into command arguments for jaeger binaries.

Internally we actually do use config files, but that's because we have a shared infra library for reading and merging configs (that is aware of things like env, data center, etc.). We also use other internal infra components for metrics, discovery, etc. so we run with a custom `main()`.

**Comment by JodeZer** [comment]
Thanks all! We will consider that seriously。
