### ISSUE TITLE
extraneous scrollbars in trace views

### ISSUE THREAD

**Issue by Dieterbe** [uber/jaeger#326]
![scrollbars](https://user-images.githubusercontent.com/20774/29113807-72bc8a3e-7cf2-11e7-98b2-581f56c93691.png)
is there a way to get rid of these scrollbars, they are cluttering up the UI. thanks. looks like some css tweaking may be needed? this is in chromium

**Comment by yurishkuro** [comment]
@tiffon please follow up

**Comment by yurishkuro** [comment]
@saminzadeh we used to have this issue in the past, not sure why it resurfaced

@Dieterbe can you provide a sample trace JSON that causes this?

**Comment by Dieterbe** [comment]
It looks like i have this all the time, irrespective of the trace.
so here's a minimal trace that also had the problem:
```
{"data":[{"traceID":"33a38a88a0833d79","spans":[{"traceID":"33a38a88a0833d79","spanID":"33a38a88a0833d79","flags":1,"operationName":"HTTP GET metrics_find","references":[],"startTime":1502314456123507,"duration":111,"tags":[{"key":"sampler.type","type":"string","value":"const"},{"key":"sampler.param","type":"bool","value":true},{"key":"span.kind","type":"string","value":"server"},{"key":"http.method","type":"string","value":"GET"},{"key":"http.url","type":"string","value":"/metrics/find?target=some.id.of.a.metric.1\u0026from=-10s"},{"key":"component","type":"string","value":"metrictank/api"},{"key":"http.status_code","type":"int64","value":422}],"logs":[],"processID":"p1","warnings":null}],"processes":{"p1":{"serviceName":"metrictank","tags":[{"key":"hostname","type":"string","value":"metrictank0"},{"key":"ip","type":"string","value":"172.21.0.9"},{"key":"jaeger.version","type":"string","value":"Go-2.9.1dev"}]}},"warnings":null}],"total":0,"limit":0,"offset":0,"errors":null}
```

btw if i remove the "overflow-scroll" class from the div elements, the scrollbar disappears.

**Comment by tiffon** [comment]
Thanks for reporting the issue.

I've made changes to address this. They should be merged within the next
few days.



On Aug 9, 2017 5:36 PM, "Dieter Plaetinck" <notifications@github.com> wrote:

It looks like i have this all the time, irrespective of the trace.
so here's a minimal trace that also had the problem:

{"data":[{"traceID":"33a38a88a0833d79","spans":[{"traceID":"33a38a88a0833d79","spanID":"33a38a88a0833d79","flags":1,"operationName":"HTTP
GET metrics_find","references":[],"startTime":1502314456123507,"duration":111,"tags":[{"key":"sampler.type","type":"string","value":"const"},{"key":"sampler.param","type":"bool","value":true},{"key":"span.kind","type":"string","value":"server"},{"key":"http.method","type":"string","value":"GET"},{"key":"http.url","type":"string","value":"/metrics/find?target=some.id.of.a.metric.1\u0026from=-10s"},{"key":"component","type":"string","value":"metrictank/api"},{"key":"http.status_code","type":"int64","value":422}],"logs":[],"processID":"p1","warnings":null}],"processes":{"p1":{"serviceName":"metrictank","tags":[{"key":"hostname","type":"string","value":"metrictank0"},{"key":"ip","type":"string","value":"172.21.0.9"},{"key":"jaeger.version","type":"string","value":"Go-2.9.1dev"}]}},"warnings":null}],"total":0,"limit":0,"offset":0,"errors":null}

btw if i remove the "overflow-scroll" class from the div elements, the
scrollbar disappears.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/uber/jaeger/issues/326#issuecomment-321388171>, or mute
the thread

**Comment by Dieterbe** [comment]
is there a PR I can follow?

**Comment by Dieterbe** [comment]
will this make its way into the docker image? i'm using the below one, and still seeing this issue
```
~ ❯❯❯ docker pull jaegertracing/all-in-one:latest
latest: Pulling from jaegertracing/all-in-one
Digest: sha256:1d8744d5f567cf1118f1fa721f0982cef829b3981cc769e358d0bcc21a22cd5f
Status: Image is up to date for jaegertracing/all-in-one:latest
~ ❯❯❯ 

```

thanks!

**Comment by yurishkuro** [comment]
we want to test it internally first, then it will be released in the official Docker image
