### ISSUE TITLE
Revisit Duration indexing and querying logic

### ISSUE THREAD

**Issue by badiib** [uber/jaeger#81]
Currently we are using an archaic methodology for storing and querying against duration (against hourly buckets that are not timestamps). We should revisit this and fix up both the code and the cassandra schema

**Comment by yurishkuro** [comment]
To clarify, the proposal is
  * define `bucket` in the db schema as `timestamp`
  * instead of converting min/max time to "hours", keep them as timestamps rounded to hours, i.e. `traceQuery.StartTimeMin.Round(time.Hour)` (with similar rounding in the writer)
  * change the loop to do `timeBucket.Sub(time.Hour)`

**Comment by badiib** [comment]
https://github.com/uber/jaeger/pull/87
